require('config.autocmds')
require('config.keymaps')
require('config.options')

require('plugins.bufferline')
require('plugins.colorscheme')
require('plugins.gitsigns')
require('plugins.indent-blankline')
require('plugins.lualine')
require('plugins.neoscroll')
require('plugins.nvim-tree')
require('plugins.nvim-web-devicons')
require('plugins.oil')
require('plugins.plenary')
require('plugins.telescope')
require('plugins.treesitter')

require('lsp')
require('lsp.lua')
require('lsp.java')
require('lsp.rust')
